name: tcpie
version: "v4.0.1"
summary: CLI tool to ping any TCP port
description: |
  tcpie is a tool to measure latency and verify the reliabilty of a TCP connection.

grade: stable
confinement: strict

apps:
  tcpie:
    command: tcpie
    plugs: [network]

parts:
  tcpie:
    plugin: nodejs
    source-tag: v4.0.1
    source: https://github.com/silverwind/tcpie.git
